---
name: CI

on:
  push:
    branches: [trunk]
  pull_request:
    branches: [trunk]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  check-and-test:
    name: Check and Test
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/inko-lang/inko:latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Check Formatting and Run Tests
        run: |
          inko --version
          inko fmt --check
          inko test
