# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

---
name: CI

on:
  push:
    branches: [trunk]
  pull_request:
    branches: [trunk]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  license-check:
    name: License Header Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Check License Headers
        uses: apache/skywalking-eyes/header@main
        with:
          config: .licenserc.yaml

  check-and-test:
    name: Check and Test
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/inko-lang/inko:latest
    needs: [license-check]

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Check Formatting and Run Tests
        run: |
          inko --version
          inko fmt --check
          inko test
